### ISSUE TITLE
Instructions to set up symbols

### ISSUE THREAD

**Issue by nanvenomous** [ndsizeif/pulsemanager#1]
I don't deem to have to speaker or arrow symbols shown in the gif.
![pulse_manager_no_symbols](https://user-images.githubusercontent.com/43622197/233437719-04218b7c-94de-4a3c-a5d2-3889346d8086.png)

Would be nice to have some instructions on how to get the full effect.

## Details
Terminals: st, alacritty
Font: JetBrainsMono Nerd Font
Version: latest main branch
Platform: Arch linux

**Comment by ndsizeif** [comment]
Thank you for bringing this to my attention.

This patched version of [JetBrainsMono Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono) is working correctly for me.
The symbols used in the program are now all material design icons, so they
should render correctly.

In the event an issue persists, or users wish not to use a patched font,
functionality has been added to disable the symbols altogether to avoid an
unsightly placeholder. The [README](https://github.com/ndsizeif/pulsemanager/blob/main/README.md) file has been updated to let others know as well. 
Please let me know of any other issues you run across.

**Comment by nanvenomous** [comment]
Awesome I just pulled the latest and it seems to have fixed it for me. Thanks!
